name: CI - Hello World

on:
  workflow_dispatch:                # runs manually

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello World"
